name: meals_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  dio: ^5.5.0+1
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.0
  loading_animation_widget: ^1.2.1
  go_router: ^14.2.1
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
