name: meals_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  dio: ^5.5.0+1
  flutter_animate: ^4.5.0
  loading_animation_widget: ^1.2.1
  go_router: ^14.2.1
  logger: ^2.4.0
  lottie: ^3.1.2
  smooth_page_indicator: ^1.2.0
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  skeletonizer: ^1.4.2
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/lottie/
    - assets/image/dummy_product/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 100